### ISSUE TITLE
repo suggestions

### ISSUE THREAD

**Issue by deangeckt** [giladfrid009/Bio-Proj#2]
- change repo name to something meaning full 
 - add to the about section some topics, e.g. elegans
 - add images to readme (features) describing the product + describe it a bit more
 - merge your local branches to a single main/master. (it seem the latest branch with the readme is a local branch...)

**Comment by giladfrid009** [comment]
* Changed repo name.
* added some about topics, but i suppose that's subjective whether it's informative or not.
* more description and readme extensions will be added later
* the latest branch is currently the main one. gilad-branch is the main branch of this repo. The rest of the branches are for development and testing purposes and will be removed later.
